version: '3.5'

# This files serves as filesystem anchor
# Including it as first .yml file makes all build paths relative to this directory ('docker')
#
# Examples:
#
#   docker-compose -f compose.yml -f hydra/compose.yml -f hydra-import/compose.yml up --build
#
# hydra-import/compose.yml is a build project and specifies its build directory relative to 'docker' parent
#